### ISSUE TITLE
Links to older docs 404 on mapserver.org

### ISSUE THREAD

**Issue by mverwijmeren** [mapserver/docs#104]
The links to the .pdf documentation on http://mapserver.org/previousversions.html result in a 404 error for all three older versions. Only the current version returns a .pdf file.

> Not Found
> 
> The requested URL /MapServer-60.pdf was not found on this server.

**Comment by havatv** [comment]
This is not a good thing. Could someone who knows the build system for the documentation and the mapserver.org site comment / take action? Perhaps @jmckenna knows something?

**Comment by tbonfort** [comment]
I'd suggest that we manually store the pdf docs on download.osgeo.org and
reference them there from the mapserver.org website. We could also add the
pdfs to the git repo, but I'm not much (at all) in favor of that as they
tend to be pretty heavy.

regards,
thomas

**Comment by jmckenna** [comment]
I used to manage all the old pdf docs yes.  Now i don't even understand where the live docs live (thomas changed the whole system and to be honest i don't understand even what server where the docs live anymore).  I would love to help again and manage :( Maybe someone needs to write a wiki page on this.  Please.

**Comment by havatv** [comment]
PDFs for versions 6.0, 5.6 and 5.4 are now linked from the download page (#115).   Should more versions be added here?  Or should other solutions be found.

**Comment by mverwijmeren** [comment]
Since #115 was obviously a duplicate of this bug, I think it's safe to simply close this one too.
