### ISSUE TITLE
Document the usage of kernel density layers

### ISSUE THREAD

**Issue by jratike80** [mapserver/docs#108]
The usage of kernel density layers is quite well documented in RFC 108. However, RFC was a plan about what and how to do and in the final implementations some details do not match with the RFC. 

Because it does not make sense to edit a plan to suit with the final solution or at least with the future development, I suggest to document the usage of kernel density layers in the Output generation section http://mapserver.org/output/index.html as a new item "Dynamic Heatmap (Kernel Density Estimation)". There is already a chapter about dynamic charting and dynamic heatmap feels to belong to same gategory.

To start with, chapters 2.1, 2.2, 2.3, and 2.8 from the RFC could be copied to new place. From example mapfiles the line "processing "KERNELDENSITY_ATTRIBUTE=VAL"" should be removed because the functionality was implemented in a different way.

**Comment by havatv** [comment]
The documentation should now be in place.  Thanks @yjacolin!
