### ISSUE TITLE
Links to previous versions of Docs are broken

### ISSUE THREAD

**Issue by tchaddad** [mapserver/docs#115]
FYI, the PDF doc links on the following page are all down (Current is working actually):
http://mapserver.org/previousversions.html#previousversions

**Comment by federicogodan** [comment]
If needed doc can be found in http://www.mapserver.org/download.html#current-release
- http://www.mapserver.org/pdf/MapServer-60.pdf
- http://www.mapserver.org/pdf/MapServer-56.pdf
- http://www.mapserver.org/pdf/MapServer-54.pdf

**Comment by havatv** [comment]
I removed the *previousversions* file and changed the link on *documentation* to point to the documentation part of *download*.  I think it is better to have the links on one place only.
Closing.
