### ISSUE TITLE
Document that PROJ_LIB configuration must come before any projection blocks.

### ISSUE THREAD

**Issue by sdlime** [mapserver/docs#124]
Since projection objects are initialized as processed it is necessary that any proj.4 related configurations must be done before any projection blocks are encountered. 

This config doesn't work:

```
MAP
  PROJECTION
    "init=epsg:3857"
  END
  CONFIG "PROJ_LIB" "C:/somedir/proj"
  ...
```

But this works fine:

```
MAP
  CONFIG "PROJ_LIB" "C:/somedir/proj"
  PROJECTION
    "init=epsg:3857"
  END
  ...
```

Steve

**Comment by havatv** [comment]
I suggest the following is added to the projection.txt file (before "Important Notes"):

    Specifying which EPSG files to use
    ----------------------------------
    
    :ref:`MAP` `CONFIG` can be used to specify the location of EPSG files:
    
    .. code-block:: mapfile

      MAP
        CONFIG "PROJ_LIB" "C:/somedir/proj"
        PROJECTION
          "init=epsg:3857"
        END # PROJECTION
        ...
    
    It is important that `CONFIG "PROJ_LIB"` comes before the `PROJECTION`
    block.

I can probably do it in some weeks time, but currently I am not able to get the github-setup on this computer to work.  So if someone else would like to add it, please go ahead.
