### ISSUE TITLE
Incorrect information about mapObj

### ISSUE THREAD

**Issue by drnextgis** [mapserver/docs#128]
From [here](http://mapserver.org/mapscript/mapscript.html#mapobj-methods)

```
convertToString() : string
Saves the object to a string. Provides the inverse option for updateFromString. .. versionadded:: 6.4
```

But `mapObj` has no `updateFromString` method.

**Comment by drnextgis** [comment]
@jmckenna if `convertToString` is not applicable for `mapObj` why this method is located within `mapObj` methods?

**Comment by jmckenna** [comment]
@drnextgis If you need a change in the source code please open an issue for that; this ticket is for documentation.

**Comment by jmckenna** [comment]
For the record, as stated in the updated doc: `convertToString` exists for the `mapObj`, but `updateFromString` does not.  If there is a problem with the source code please file a new ticket in /mapserver/issues/
