### ISSUE TITLE
Update Mapserver documentation to reflect the changes in character encoding support

### ISSUE THREAD

**Issue by havatv** [mapserver/docs#147]
LABEL ENCODING has been removed and LAYER ENCODING introduced (http://mapserver.org/development/rfc/ms-rfc-103.html and https://github.com/mapserver/mapserver/issues/4758).  This has consequences for the documentation.  The documentation of LAYER ENCODING has been taken care of in #146, but LABEL ENCODING needs to be removed and "Display of International Characters in MapServer" and "Expressions" must be updated.

**Comment by havatv** [comment]
@jmckenna, could you update "Display of International Characters in Mapserver" (mapfile/labelencoding.txt) to reflect the way character encoding is handled in Mapserver 7?

**Comment by jmckenna** [comment]
@havatv I'm on it
