### ISSUE TITLE
Update documentation for LAYER-CLUSTER / LAYER-Processing

### ISSUE THREAD

**Issue by ruhri** [mapserver/docs#149]
In LAYER-CLUSTER:SupportedProcessingOptions please change “CLUSTER_GET_ALL_SHAPES” to "CLUSTER_GET_ALL_SHAPES=ON".

There should also be added following new Processing Options (as mentioned in https://github.com/mapserver/mapserver/issues/4822):
- processing option CLUSTER_KEEP_LOCATIONS=ON to set whether the location of the Cluster shape should be preserved (no averaging)

- processing option CLUSTER_USE_MAP_UNITS=ON to provide scale independent clustering (maxdistance and the buffer parameters are specified in map units)

To achieve the behaviour of mapserver at **WMS-GetFaetureInfo-Request** on a clustered layer to throw back attributes of the base-features and not the aggregated features from the cluster-Point, two processing Options are needed, for example (having a dataset which has attributes attribute_x, attribute_y and attribute_z):
- PROCESSING "CLUSTER_GET_ALL_SHAPES=ON"
- PROCESSING "ITEMS=attribute_x,attribute_y,attribute_z"
which would give attribute_x, attribute_y and attribute_z for each base-Feature of the Cluster-Point.

LAYER-Processing Directives should also be updated or referenced to LAYER-CLUSTER.

THX

**Comment by jmckenna** [comment]
Thanks for reporting this.  Taking a look...

**Comment by jmckenna** [comment]
I've added the clustering options to the Cluster document, including notes for GetFeatureInfo requirements, and documented the processing items in the Layer object.  I also tested this with MapServer 7.0.1 (MS4W 3.1.4).

**Comment by ruhri** [comment]
Thank You Jeff,
it took me a while to get these features working. I'm sure, someone other will need less time now...
