### ISSUE TITLE
translated Ukraine pages using incorrect "UK" country code

### ISSUE THREAD

**Issue by jmckenna** [mapserver/docs#150]
- should actually be "UA" https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#UA

**Comment by jmckenna** [comment]
Initially reported on the mailing list: http://osgeo-org.1560.x6.nabble.com/Mapserver-filter-expression-by-DATE-td5280038.html

**Comment by jmckenna** [comment]
This could be tricky because this is all tied to a Transifex project.  I have requested access to join the Transifex "team": https://www.transifex.com/mapserver/mapserver-doc/

**Comment by jmckenna** [comment]
Possibly we need to change from the Transifex "UK" code to the Transifex "uk_UA" code: https://www.transifex.com/explore/languages/

**Comment by jmckenna** [comment]
Actually, since Ukrainian translations are currently at 0%, maybe the easiest solution is to remove the Ukraine part for now?  Thoughts?  (again, I currently have no access to the Transifex "team")

**Comment by jmckenna** [comment]
@yjacolin what are your thoughts?

**Comment by yjacolin** [comment]
First I will give you transifex account access as it is better to share it with you. I have nothing against close the Ukraine part. But don't we find a solution for this problem? I will look into the QGIS process to compare.

**Comment by yjacolin** [comment]
@jmckenna I need your transifex account :)

**Comment by yjacolin** [comment]
Found it, you are now a maintener of Mapserver-doc transifex project.

**Comment by jmckenna** [comment]
thanks @yjacolin

**Comment by yjacolin** [comment]
it seems I forget something, thank :)

**Comment by jmckenna** [comment]
This was still haunting us; I noticed an old "MapServer 7.4.1" result deep down in Google results, in Russian language and pointing to https://mapserver.org/uk/ and still displaying valid html page for that old document version.  I searched on mapserver.org server and found an old /uk/ folder in htdocs, so I've removed that folder.   Google search engine will soon remove that result I am sure.
