### ISSUE TITLE
LINEJOIN documentation "none"

### ISSUE THREAD

**Issue by LarsSchy** [mapserver/docs#160]
LINEJOIN [round|miter|bevel] should be

LINEJOIN [round|miter|bevel|none]

in the style description page as described in the "Cartographical Symbol Construction with MapServer" page.

**Comment by jmckenna** [comment]
Added to the LINEJOIN parameter of the STYLE object in the mapfile documentation (see http://mapserver.org/mapfile/style.html).

thanks @LarsSchy !
