### ISSUE TITLE
Tile Mode is not mentioned in MapServer CGI Controls

### ISSUE THREAD

**Issue by drnextgis** [mapserver/docs#161]
MapServer CGI Controls [page](http://mapserver.org/cgi/controls.html) contains different values of `MODE` variable. But `tile` [mode](http://mapserver.org/output/tile_mode.html) is not mentioned.

**Comment by havatv** [comment]
`tilemode` and `tile` also seem to be missing on the CGI Controls page. Is this deliberate? (encourage use of mapcache)

**Comment by geographika** [comment]
I'd imagine it happened simply as the TILE mode is much more recent than the others. 
Should the MODEs be at least given there own subsection on the CGI Controls page? They are a powerful, yet pretty hidden feature of MapServer (at least to newer users).

**Comment by msmitherdc** [comment]
It’s in the output section. http://mapserver.org/output/tile_mode.html

**Comment by geographika** [comment]
@havatv - I think this can be closed now?

**Comment by havatv** [comment]
Thank you for the reminder, @geographika!
