### ISSUE TITLE
Add <xml...> to WFS stored query examples

### ISSUE THREAD

**Issue by havatv** [mapserver/docs#163]
Subject: Re: [mapserver-users] About the WFS 2.0 stored query example
Date: Wed, 21 Dec 2016 11:36:55 +0000
From: Rahkonen Jukka (MML) <jukka.rahkonen@maanmittauslaitos.fi>

For making Mapserver to accept the definition of the stored query from a saved XML file I had to add xml header line

    <?xml version="1.0" encoding="UTF-8"?>
     <StoredQueryDescription xmlns:xs="http://www.w3.org/2001/XMLSchema"  xmlns:gml="http://www.opengis.net/gml/3.2" id="bboxstoredquery">

It was not self-evident for me. Perhaps the examples in http://mapserver.org/ogc/wfs_server.html#stored-queries-wfs-2-0 could have this edit for making them more copy-paste ready.

**Comment by havatv** [comment]
The two examples have been updated with a new first line.

**Comment by jratike80** [comment]
Thank you, I believe it is good to have the XML header line included even my description was wrong. At least it may help with titles and abstracts which have non-ASCII characters. Missing line is not the thing that prevents Mapserver from parsing the definition file but there is something else going on with that.
