### ISSUE TITLE
Add info about scale-dependant string substitutions

### ISSUE THREAD

**Issue by frodewj** [mapserver/docs#178]
In http://mapserver.org/mapfile/layer.html there is no information about scale-dependant string substitutions (http://mapserver.org/development/rfc/ms-rfc-86.html)

**Comment by havatv** [comment]
Thanks, @frodewj!
SCALETOKEN has been added to the LAYER documentation.  References the RFC and includes one of the RFC examples.
The SCALETOKEN object has not been documented in a separate file.
