### ISSUE TITLE
Add documentation for SCALEBAR / OFFSET keyword

### ISSUE THREAD

**Issue by theduckylittle** [mapserver/docs#200]
When https://github.com/mapserver/mapserver/pull/5489 is merged, the new OFFSET keyword for SCALEBAR will need to be documented.

To be as clear as possible, the OFFSET directive will attempt to bring the scalebar closer to the center of the map no matter the POSITION setting.  To examples:
- If POSITION is LL then OFFSET 5 5 END will shift the scalebar 5 pixels up and 5 pixels to the right.
- If POSITION is  UR then OFFSET 5 5 END will shift the scalebar 5 pixels down and 5 pixels to the left.

**Comment by havatv** [comment]
Thanks! Documentation added to master.
