### ISSUE TITLE
Add information about !BOX! variable in DATA parameter

### ISSUE THREAD

**Issue by yjacolin** [mapserver/docs#226]
!BOX! could be used to filter data with the current BOX in Data parameter in MapServer.
Example:
```
DATA .... WHERE ST_Intersects(wkb_geometry,!BOX!)
```

**Comment by jratike80** [comment]
Could you also document when !BOX! is needed or useful. As far as I know at least when PostGIS, SpatiaLite, or GeoPackage are used as data source the BBOX filter (bounding boxes intersect, && with PostGIS) is used automatically. Is it just when an accurate result is needed? BBOX tends to select a little bit more that ST_Intersects. I suppose that by adding ST_Intersects(wkb_geometry,!BOX!) the queries will be a little bit slower but the result will not contain any non-intersecting features.

**Comment by yjacolin** [comment]
Thanks for you feedback indeed I need to explain an use case.

We have a complexe query with subqueries. One of this subquery is quiet long to finish but the BBOX filter only apply in the final query and it is not used in the subqueries.
