### ISSUE TITLE
Update UNIX/Linux install docs to note that libgdal-dev is required.

### ISSUE THREAD

**Issue by sdlime** [mapserver/docs#236]
See https://github.com/mapserver/mapserver/issues/5539#issuecomment-388436629 for more information. Looks like this change applies to 7.0+.

--Steve

**Comment by SunveerSingh** [comment]
Hello, I would like to work on this issue, we will add libgdal-dev(Required) in highly Highly Recommended Libraries here: https://mapserver.org/installation/unix.html
