### ISSUE TITLE
Note for MapCache configuration documentation

### ISSUE THREAD

**Issue by almaniac** [mapserver/docs#254]
A note should be added to the configuration File page (https://mapserver.org/mapcache/config.html) to indicate that the mapcache.xml file is only read when Apache starts. 

This would be helpful for people new to configuring MapCache, and removes the assumption that they will be familiar with how Apache works.

I'd suggest something like this under the example at the top of the page:

Note: the MapCache configuration file is only read when the Apache web server starts and the MapCache module is loaded.  If you modify this file you will have to restart Apache for the changes to take effect.

**Comment by jmckenna** [comment]
@almaniac are you able to create a pull request for this change?

**Comment by SunveerSingh** [comment]
Please see the pull request issue has been fixed!

**Comment by jmckenna** [comment]
Fixed by @SunveerSingh
