### ISSUE TITLE
Give the `VALIDATION` block its own documentation page

### ISSUE THREAD

**Issue by homme** [mapserver/docs#26]
`VALIDATION` blocks provide quite a bit of functionality that is currently poorly documented if at all: a quick scan through `mapfile.c` shows specifying `expression`, `group`, `keyimage`, `template`, `text`, `title` and `immutable` validation strings affects mapserver behaviour. Centralising documentation for these parameters would be useful, with links to the more specialised Runtime Substitution documentation where appropriate.

**Comment by geographika** [comment]
@havatv - is there any reason why the validation page can't be added to the main docs? I was thinking of making a new page for `SCALETOKEN ` also, but not sure if there are conventions on which blocks merit a new page.

**Comment by havatv** [comment]
No reason apart from me being unsure that it is ready for publication.  If @sdlime and @jmckenna could have a look at it and they agree that it is ready for publication, we can add it to the web site.

**Comment by havatv** [comment]
I just tried to find the validation.txt file, but it is not in the mapfile directory.  The file can be reconstructed from the commit, but I will wait until we get a response.

**Comment by sdlime** [comment]
@havatv, sorry but what file should I be reviewing? --Steve

**Comment by havatv** [comment]
@sdlime, the file is gone, but you will find the contents in the commit (3b8e0da).

**Comment by geographika** [comment]
Built page at: https://dl.dropboxusercontent.com/u/29280207/mapserver/mapfile/validation.html

**Comment by sdlime** [comment]
I think the page looks great - the topic certainly warrants the detailed discussion. Two questions:

1. There is a lot of overlap with the run-time substitution page. Perhaps that page could be more tactical, that is, addressing strategies and use cases with the syntax being in the validation block.
2. There is a use case not covered in the docs that could (should?) be - setting validation for CGI-based mapfile changes (http://mapserver.org/cgi/controls.html#changing-map-file-parameters-via-a-form-or-a-url). At worst we should reference that content.

Steve

**Comment by havatv** [comment]
OK.  I will give it a go.

**Comment by havatv** [comment]
In the latest commit I added the file and linked it into the documentation.  I have not yet adressed @sdlime's two questions yet.

**Comment by havatv** [comment]
The validation block now has its own documentation page, and I have added issues for @sdlime's two questions.  Closing.
