### ISSUE TITLE
PHP documentation r

### ISSUE THREAD

**Issue by arthur-clifford** [mapserver/docs#276]
Originally miss-filed here; https://github.com/mapserver/mapserver/issues/5814

With version 5.4 my understanding was that PHP7 mapscript should be part of the release. But, the PHP MapScript page still has the warning about still being under development.

Also, the PHP part of the installation instructions are still referring to php5 instead of php 7.
https://mapserver.org/installation/php.html#php-install
Note it was last updated: 2016-06-15

Now that you have gotten things working with PHP 7, it would be good if the PHP related documentation were reviewed for any changes that would help reflect the support for PHP 7.

(possibly related to: https://github.com/mapserver/docs/issues/41)

**Comment by jmckenna** [comment]
@arthur-clifford I made a pass through and updated the docs.   Also, as you travel down this path remember that Pull Requests to the docs are encouraged :)   Thanks for reporting this.
