### ISSUE TITLE
demo.mapserver.org down

### ISSUE THREAD

**Issue by jmckenna** [mapserver/docs#311]
- received a notice overnight from a bot that our https://demo.mapserver.org/ is down
 - those demo services are today heavily used by community
 - also those services are leveraged internally through msautotest as well as throughout the MapServer documentation

**Comment by jmckenna** [comment]
Fixed.  
- restarted Apache services
- recompiled MapServer, now all services leverage version 7.4.3
- updated msautotest's world.map service to leverage version 7.4.3 (from 5.6.5)  https://demo.mapserver.org/cgi-bin/mapserv?map=/osgeo/mapserver/msautotest/world/world.map&SERVICE=WMS&REQUEST=GetCapabilities
Seems like a good thing to do on leap year day!

**Comment by jbo-ads** [comment]
This needs an update of msautotest, see [MapServer pull request #6010](https://github.com/mapserver/mapserver/pull/6010)

**Comment by jmckenna** [comment]
thank you for this @jbo-ads
