### ISSUE TITLE
loadLayer() error on opening tutorial's links and examples

### ISSUE THREAD

**Issue by jey-GIS** [mapserver/docs#312]
Tutorial (starting from example1-4 and futher) referes to old mapfiles what contain several layers with LAYER.TYPE = ANNOTATION (despite it's declared as depricated from version 6.2) resulting in empty page with error message: "loadLayer(): Unknown identifier. Annotation Layers have been removed. To obtain same functionality, use a layer with label->styles and no class->styles".
The same error for Sections 2-4 (eg for link to  Example 2.1 - Pan and Zoom Controls
https://demo.mapserver.org/cgi-bin/mapserv?map=/osgeo/mapserver/tutorial/htdocs/example2.map&layer=states&zoom=0&mode=browse&root=/tutorial&program=/cgi-bin/mapserv&map_web=template+example2-1.html

**Comment by jmckenna** [comment]
Thanks for reporting this @jey-GIS  I'll update these sections and report back

**Comment by jey-GIS** [comment]
Thank you for so good product. It's a pity that its tutorial suffers from such small error.. 
For examples in Section1 it's not a big deal to correct it by oneself as a kind of home task :), but futher Sections 2-4 use https://demo.mapserver.org to explain different aspects of templating and quering, and it requires to set up all those web-server parameters and libraries localy just to be able to read tutorial's example.

**Comment by jmckenna** [comment]
Actually your errors are brand new - you just happened to test this at the exact same time that I upgraded the /mapserv?  executable on that server, from MapServer 5.6.5 to 7.4.3 :)   So no problem, I will update the tutorial to match the excecutable demo links :)

**Comment by jmckenna** [comment]
And this is a much-needed upgrade for the tutorial, as you had mentioned earlier! :)

**Comment by jmckenna** [comment]
Fixed.  Many changes including:
- removed all ANNOTATION layers
- updated all layer classes to handle highway shields with MapServer 7
- live tutorial pages updated at https://mapserver.org/tutorial/
- all updated mapfiles and data available to download at http://download.osgeo.org/mapserver/docs/mapserver-tutorial.zip
- various changes made to get legends, WMS layers, labeling working with MapServer 7
- also rebuilt mapserv on demo server to properly handle WMS with HTTPS etc.

![Annotation 2020-03-14 095643](https://user-images.githubusercontent.com/1611709/76682399-abee0480-65da-11ea-8793-59014ac89ca5.png)


It's actually a great resource users can download with over 12 working mapfiles, highway shields, labeling, WMS, and adapt for their own data.
